# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a390d651825c642518ca581ba64c579"
name = "Form Builder HUB"
handle = "form-builder-hub"
application_url = "https://vulnerable-bad-hk-browse.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sahil-app-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vulnerable-bad-hk-browse.trycloudflare.com/auth/callback",
  "https://vulnerable-bad-hk-browse.trycloudflare.com/auth/shopify/callback",
  "https://vulnerable-bad-hk-browse.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
