# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a390d651825c642518ca581ba64c579"
application_url = "https://estimate-revenge-gibson-male.trycloudflare.com"
embedded = true
name = "SyncForm"
handle = "syncForm"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-himanshu.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://diff-du-royal-millennium.trycloudflare.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
  uri = "https://diff-du-royal-millennium.trycloudflare.com/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,read_themes,write_customers,write_orders,write_products,write_themes"

[auth]
redirect_urls = [
  "https://estimate-revenge-gibson-male.trycloudflare.com/auth/callback",
  "https://estimate-revenge-gibson-male.trycloudflare.com/auth/shopify/callback",
  "https://estimate-revenge-gibson-male.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = true
